### ISSUE TITLE
Run firsts JMX scripts with BlazeMeter

### ISSUE THREAD

**Issue by lacostenycoder** [thoroughcare/scale-testing#1]
Run BlazeMeter tests for:
* Login in the ThoroughCare application
* TimeLogs to a couple of patient
* Edit a Patient information

**Comment by moisesdavid3** [comment]
The team had some issues trying to record the JMX scripts using the proxy server from the BlazeMeter webpage. So, we look for other options and we found that the scripts can be easily recorded with the BlazeMeter Chrome plugin. It can be found here: https://chrome.google.com/webstore/detail/blazemeter-the-continuous/mbopgmdnpcbohhpnfglgohlbhfongabi?utm_source=chrome-ntp-icon
